<a href="https://colab.research.google.com/github/raja-kumar-jha/numpy-fundamentals/blob/main/numpy_fundamentels.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# 1. Install the library
!pip install watermark

# 2. Load the extension
%load_ext watermark

# 3. Use it to display your info
%watermark -a "Raja Kumar Jha" -u -d -v -p numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 63.6 MB/s eta 0:00:00
Author: Raja Kumar Jha

Last updated: 2026-08-07

Python implementation: CPython
Python version       : 3.12.13
IPython version      : 7.34.0

numpy: 2.0.2



# Numpy Fundamentals

## Objective
To understand and practice core Numpy concepts used in data science and machine learning.

# Import Numpy

In [2]:
import numpy as np

# Version of NumPy
print(f'numpy version: {np.__version__}')

numpy version: 2.0.2


# Indexing

In [3]:
a = np.array([1., 2., 3., 4., 5., 6., 7., 8.]) #list
a

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [4]:
a[0]

np.float64(1.0)

In [5]:
a[0] = 10
a

array([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [6]:
a[:3]

array([10.,  2.,  3.])

In [7]:
b = a[3:]
b

array([4., 5., 6., 7., 8.])

In [8]:
b[0] = 40
a

array([10.,  2.,  3., 40.,  5.,  6.,  7.,  8.])

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[3:]

# Check if b is a view of a
print(b.base is a)    # Output: True

# Create an actual copy
c = a[3:].copy()
print(c.base is a)    # Output: False (c owns its data)

True
False


In [10]:
a = np.array((1,2)) #tuple
a

array([1, 2])

In [11]:
a = np.array({1,2,3,4,5}) # set
a

array({1, 2, 3, 4, 5}, dtype=object)

In [12]:
a = np.array(1)
a

array(1)

In [13]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
a[1,3]

np.int64(8)

# Array attributes

This section covers the `ndim`, `shape`, `size`, and `dtype` attributes of an array.



In [15]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [16]:
a.ndim

2

In [17]:
a.shape

(3, 4)

In [18]:
# len(a.shape) is equal to a.ndim
len(a.shape)

2

In [19]:
len(a.shape) == a.ndim

True

In [20]:
a.size

12

In [21]:
import math
math.prod(a.shape)

12

In [22]:
# math.prod(a.shape) == a.size
math.prod(a.shape) == a.size

True

In [23]:
a.dtype # "int" for integer, "64" for 64-bit

dtype('int64')

# Creating Array

This section covers `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`



In [24]:
np.zeros(2)

array([0., 0.])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
# Create an empty array with 2 elements
np.empty(2)  # may vary

array([1., 1.])

In [27]:
# You can create an array with a range of elements
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [28]:
np.arange(1,10,2) # first no. last no. and step size

array([1, 3, 5, 7, 9])

In [29]:
# we can also use np.linspace() to create an array with values that are spaced linearly in a specified interval
np.linspace(1, 2, num= 5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

**Specifying our data type**

In [30]:
x = np.ones(2, dtype = np.int32)
x

array([1, 1], dtype=int32)

In [31]:
y = np.zeros(3, dtype= np.float64)
y.dtype

dtype('float64')

# Adding, removing, and sorting elements

This section covers `np.sort()`, `np.concatenate()`

In [32]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [33]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [35]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [37]:
np.concatenate((x,y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In order to remove elements from an array, it’s simple to use indexing to select the elements that you want to keep.

# How do you know the shape and size of an array?

This section covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

In [38]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [39]:
array_example.ndim

3

In [40]:
array_example.shape

(3, 2, 4)

In [41]:
array_example.size

24

# Can you reshape an array?

In [42]:
arr = np.array([[[1,2,3,4],[4,5,6,7]],
                [[4,5,6,7],[8,4,5,6]]])
arr

array([[[1, 2, 3, 4],
        [4, 5, 6, 7]],

       [[4, 5, 6, 7],
        [8, 4, 5, 6]]])

In [43]:
arr.reshape(16) # Reshapes to a 1D array with 16 elements
# Or, if you want a 2D array, you could use arr.reshape(4, 4)

array([1, 2, 3, 4, 4, 5, 6, 7, 4, 5, 6, 7, 8, 4, 5, 6])

In [44]:
arr.reshape(2,4,2)

array([[[1, 2],
        [3, 4],
        [4, 5],
        [6, 7]],

       [[4, 5],
        [6, 7],
        [8, 4],
        [5, 6]]])

# How to convert a 1D array into a 2D array (how to add a new axis to an array)

This section covers `np.newaxis`, `np.expand_dims`

In [45]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.shape

(9,)

In [46]:
a2 = a[:, np.newaxis]
a2.shape

(9, 1)

In [47]:
a3 = a[np.newaxis,:]
a3.shape

(1, 9)

In [48]:
a3

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [49]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [50]:
b = np.expand_dims(a, axis=0)
b.shape

(1, 6)

In [51]:
b1 = np.expand_dims(a, axis=1 )
b1.shape

(6, 1)

# Indexing and slicing

In [52]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
d[1]

np.int64(2)

In [54]:
d[1:2]

array([2])

In [55]:
d[1:5]

array([2, 3, 4, 5])

In [56]:
d[::1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
d[::3]

array([ 1,  4,  7, 10])

In [58]:
d[-2]

np.int64(9)

In [59]:
d[-2:]

array([ 9, 10])

In [60]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
print(a[a<5])

[1 2 3 4]


In [62]:
print(a[2<a])

[ 3  4  5  6  7  8  9 10 11 12]


In [63]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [64]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


Or you can select elements that satisfy two conditions using the `&` and `| `operators:

In [65]:
s = a[(a>4) & (a<9)]
s

array([5, 6, 7, 8])

In [66]:
s = a[(a>3) | (a==5)]
s

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [67]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [69]:
b = np.nonzero(a<5)
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [70]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Original array a:")
print(a)

# Let's first look at the boolean array produced by the condition `a < 5`
condition_array = (a < 5)
print("\nBoolean array (a < 5):")
print(condition_array)

# Now, apply np.nonzero()
indices = np.nonzero(a < 5)
print("\nResult of np.nonzero(a < 5):")
print(indices)

# How to use these indices to get the values:
# The first array in 'indices' contains the row indices
# The second array in 'indices' contains the column indices
print("\nElements corresponding to these indices:")
print(a[indices])

Original array a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Boolean array (a < 5):
[[ True  True  True  True]
 [False False False False]
 [False False False False]]

Result of np.nonzero(a < 5):
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

Elements corresponding to these indices:
[1 2 3 4]


As you can see from the output:
*   `np.nonzero(a < 5)` returns a tuple of two arrays. The first array `(array([0, 0, 0, 0]))` gives the row indices where the condition `a < 5` is `True`.
*   The second array `(array([0, 1, 2, 3]))` gives the corresponding column indices where the condition `a < 5` is `True`.

This means that the elements at `(0,0)`, `(0,1)`, `(0,2)`, and `(0,3)` in array `a` satisfy the condition `a < 5`. When you use `a[indices]`, NumPy gathers these elements for you.

In [71]:
c = np.nonzero(a>5)
c

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))